function onDocumentLoad(){new Runner(".interstitial-wrapper")}!
function(){"use strict";navigator.userAgent.match(/AppleWebKit.*Mobile.*/)&&navigator.userAgent.match(/AppleWebKit/);
function m(t,i){if(m.instance_)
return m.instance_;(m.instance_=this).outerContainerEl=document.querySelector(t),
this.containerEl=null,
this.snackbarEl=null,
this.config=i||m.config,
this.dimensions=m.defaultDimensions,
this.canvas=null,
this.canvasCtx=null,
this.tRex=null,
this.distanceMeter=null,
this.distanceRan=0,
this.highestScore=0,
this.time=0,
this.runningTime=0,
this.msPerFrame=1e3/s,
this.currentSpeed=this.config.SPEED,
this.obstacles=[],
this.activated=!1,
this.playing=!1,
this.crashed=!1,
this.paused=!1,
this.inverted=!1,
this.invertTimer=0,
this.resizeTimerId_=null,
this.bdayFlashTimer=null,
this.playCount=0,
this.audioBuffer=null,
this.soundFx={},
this.audioContext=null,
this.images={},
this.imagesLoaded=0,
this.isDisabled()?
this.setupDisabledRunner():
this.loadImages()}window.Runner=m;
var e=600,s=60,T=1<window.devicePixelRatio,n=/iPad|iPhone|iPod/.test(window.navigator.platform),h=/Android/.test(window.navigator.userAgent)||n;
function a(t,i){return Math.floor(Math.random()*(i-t+1))+t}
function o(){return n?(new Date).getTime():performance.now()}
function p(t,i,s,e){
	this.canvas=t,
	this.canvasCtx=t.getContext("2d"),
	this.canvasDimensions=e,
	this.textImgPos=i,
	this.restartImgPos=s,
	this.draw()}
function l(t,i){return new I(t.x+i.x,t.y+i.y,t.width,t.height)}
function g(t,i,s){t.save(),t.strokeStyle="#f00",t.strokeRect(i.x,i.y,i.width,i.height),t.strokeStyle="#0f0",t.strokeRect(s.x,s.y,s.width,s.height),t.restore()}
function E(t,i){var s=!1,e=(t.x,t.y,i.x);i.y;
return s=t.x<e+i.width&&t.x+t.width>e&&t.y<i.y+i.height&&t.height+t.y>i.y?!0:s}
function I(t,i,s,e){this.x=t,this.y=i,this.width=s,this.height=e}
function r(t,i,s,e,n,h,o){
	this.canvasCtx=t,
	this.spritePos=s,
	this.typeConfig=i,
	this.gapCoefficient=n,
	this.size=a(1,r.MAX_OBSTACLE_LENGTH),
	this.dimensions=e,
	this.remove=!1,
	this.xPos=e.WIDTH+(o||0),
	this.yPos=0,
	this.width=0,
	this.collisionBoxes=[],
	this.gap=0,
	this.speedOffset=0,
	this.imageSprite="SNACK"==this.typeConfig.type?m.bdayImageSprite:m.imageSprite,
	this.currentFrame=0,
	this.timer=0,
	this.init(h)}
function f(t,i){
	this.canvas=t,
	this.canvasCtx=t.getContext("2d"),
	this.imageSprite=m.imageSprite,
	this.spritePos=i,
	this.xPos=0,
	this.yPos=0,
	this.groundYPos=0,
	this.currentFrame=0,
	this.currentAnimFrames=[],
	this.blinkDelay=0,
	this.blinkCount=0,
	this.animStartTime=0,
	this.timer=0,
	this.msPerFrame=1e3/s,
	this.config=f.config,
	this.status=f.status.WAITING,
	this.jumping=!1,
	this.ducking=!1,
	this.jumpVelocity=0,
	this.reachedMinHeight=!1,
	this.speedDrop=!1,
	this.jumpCount=0,
	this.jumpspotX=0,
	this.bdayModeActive=!1,
	this.flashing=!1,
	this.init()}
function c(t,i,s){
	this.canvas=t,
	this.canvasCtx=t.getContext("2d"),
	this.image=m.imageSprite,
	this.spritePos=i,
	this.x=0,
	this.y=5,
	this.currentDistance=0,
	this.maxScore=0,
	this.highScore=0,
	this.container=null,
	this.digits=[],
	this.achievement=!1,
	this.defaultString="",
	this.flashTimer=0,
	this.flashIterations=0,
	this.invertTrigger=!1,
	this.config=c.config,
	this.maxScoreUnits=this.config.MAX_DISTANCE_UNITS,
	this.init(s)}
function d(t,i,s,e){
	this.canvas=t,
	this.canvasCtx=this.canvas.getContext("2d"),
	this.spritePos=i,
	this.containerWidth=s,
	this.xPos=s,
	this.yPos=0,
	this.remove=!1,
	this.cloudGap=a(d.config.MIN_CLOUD_GAP,d.config.MAX_CLOUD_GAP),
	this.isBalloon=e,
	this.imageSprite=e?m.bdayImageSprite:m.imageSprite,
	this.init()}
function u(t,i,s){
	this.spritePos=i,
	this.canvas=t,
	this.canvasCtx=t.getContext("2d"),
	this.xPos=s-50,
	this.yPos=30,
	this.currentPhase=0,
	this.opacity=0,
	this.containerWidth=s,
	this.stars=[],
	this.drawStars=!1,
	this.placeStars()}
function C(t,i){
	this.spritePos=i,
	this.canvas=t,
	this.canvasCtx=t.getContext("2d"),
	this.sourceDimensions={},
	this.dimensions=C.dimensions,
	this.sourceXPos=[this.spritePos.x,
	this.spritePos.x+this.dimensions.WIDTH],
	this.xPos=[],this.yPos=0,
	this.bumpThreshold=.5,
	this.setSourceDimensions(),
	this.draw()}
function D(t,i,s,e){
	this.canvas=t,
	this.canvasCtx=this.canvas.getContext("2d"),
	this.config=D.config,
	this.dimensions=s,
	this.gapCoefficient=e,
	this.obstacles=[],
	this.obstacleHistory=[],
	this.horizonOffsets=[0,0],
	this.cloudFrequency=this.config.CLOUD_FREQUENCY,
	this.spritePos=i,
	this.nightMode=null,
	this.bdayModeActive=!1,
	this.clouds=[],
	this.cloudSpeed=this.config.BG_CLOUD_SPEED,
	this.horizonLine=null,
	this.init()}m.config={
		ACCELERATION:.001,
		BG_CLOUD_SPEED:.2,
		BOTTOM_PAD:10,
		BOTTOM_PAD_BDAY:26,
		BDAY_FLASH_DURATION:500,
		BDAY_Y_POS_ADJUST:16,
		CLEAR_TIME:3e3,
		CLOUD_FREQUENCY:.5,
		GAMEOVER_CLEAR_TIME:750,
		GAP_COEFFICIENT:.6,
		GRAVITY:.6,
		INITIAL_JUMP_VELOCITY:12,
		INVERT_FADE_DURATION:12e3,
		INVERT_DISTANCE:700,
		MAX_BLINK_COUNT:3,
		MAX_CLOUDS:6,
		MAX_OBSTACLE_LENGTH:3,
		MAX_OBSTACLE_DUPLICATION:2,
		MAX_SPEED:13,
		MIN_JUMP_HEIGHT:35,
		MOBILE_SPEED_COEFFICIENT:1.2,
		RESOURCE_TEMPLATE_ID:"audio-resources",
		SPEED:6,
		SPEED_DROP_COEFFICIENT:3,
		ARCADE_MODE_INITIAL_TOP_POSITION:35,
		ARCADE_MODE_TOP_POSITION_PERCENT:.1},
		m.defaultDimensions={WIDTH:e,HEIGHT:150},
		m.classes={ARCADE_MODE:"arcade-mode",
		CANVAS:"runner-canvas",
		CONTAINER:"runner-container",
		CRASHED:"crashed",
		ICON:"icon-offline",
		INVERTED:"g-dark",
		SNACKBAR:"snackbar",
		SNACKBAR_SHOW:"snackbar-show",
		TOUCH_CONTROLLER:"controller"},
		m.spriteDefinition={
			LDPI:{
				BALLOON:{x:417,y:29},
				CACTUS_LARGE:{x:332,y:2},
				CACTUS_SMALL:{x:228,y:2},
				CLOUD:{x:86,y:2},
				HORIZON:{x:2,y:54},
				MOON:{x:484,y:2},
				PTERODACTYL:{x:134,y:2},
				RESTART:{x:2,y:2},
				TEXT_SPRITE:{x:655,y:2},
				TREX:{x:848,y:2},
				TREX_BDAY:{x:0,y:0},
				SNACK:{x:384,y:22},
				STAR:{x:645,y:2}},
			HDPI:{
				BALLOON:{x:834,y:58},
				CACTUS_LARGE:{x:652,y:2},
				CACTUS_SMALL:{x:446,y:2},
				CLOUD:{x:166,y:2},
				HORIZON:{x:2,y:104},
				MOON:{x:954,y:2},
				PTERODACTYL:{x:260,y:2},
				RESTART:{x:2,y:2},
				TEXT_SPRITE:{x:1294,y:2},
				TREX:{x:1678,y:2},
				TREX_BDAY:{x:0,y:0},
				SNACK:{x:768,y:44},
				STAR:{x:1276,y:2}}},
m.sounds={
	BUTTON_PRESS:"offline-sound-press",
	HIT:"offline-sound-hit",
	SCORE:"offline-sound-reached"},
m.keycodes={
	JUMP:{38:1,32:1},
	DUCK:{40:1},
	RESTART:{13:1}},
m.events={
	ANIM_END:"webkitAnimationEnd",
	CLICK:"click",
	KEYDOWN:"keydown",
	KEYUP:"keyup",
	POINTERDOWN:"pointerdown",
	POINTERUP:"pointerup",
	RESIZE:"resize",
	TOUCHEND:"touchend",
	TOUCHSTART:"touchstart",
	VISIBILITY:"visibilitychange",
	BLUR:"blur",
	FOCUS:"focus",
	LOAD:"load"},
m.prototype={isDisabled:function(){return!1},
setupDisabledRunner:function(){this.containerEl=document.createElement("div"),
this.containerEl.className=m.classes.SNACKBAR,
this.outerContainerEl.appendChild(this.containerEl),
document.addEventListener(m.events.KEYDOWN,function(t){m.keycodes.JUMP[t.keyCode]&&(this.containerEl.classList.add(m.classes.SNACKBAR_SHOW),
document.querySelector(".icon").classList.add("icon-disabled"))}.bind(this))},
updateConfigSetting:function(t,i){if(t in this.config&&null!=i)
switch(this.config[t]=i,t){case"GRAVITY":case"MIN_JUMP_HEIGHT":case"SPEED_DROP_COEFFICIENT":this.tRex.config[t]=i;
break;case"INITIAL_JUMP_VELOCITY":this.tRex.setJumpVelocity(i);
break;case"SPEED":this.setSpeed(i)}},loadImages:function(){T?(m.imageSprite=document.getElementById("offline-resources-2x"),
m.bdayImageSprite=document.getElementById("offline-resources-bday-2x"),
this.spriteDef=m.spriteDefinition.HDPI):(m.imageSprite=document.getElementById("offline-resources-1x"),
m.bdayImageSprite=document.getElementById("offline-resources-bday-1x"),
this.spriteDef=m.spriteDefinition.LDPI),m.imageSprite.complete?this.init():m.imageSprite.addEventListener(m.events.LOAD,
this.init.bind(this))},
loadSounds:function(){if(!n){this.audioContext=new AudioContext;document.getElementById(this.config.RESOURCE_TEMPLATE_ID).content;
for(var t in m.sounds){var i=document.getElementById(m.sounds[t]);
this.soundFx[t]=i}}},setSpeed:function(t){var i,s=t||this.currentSpeed;
this.dimensions.WIDTH<e?(i=s*this.dimensions.WIDTH/e*this.config.MOBILE_SPEED_COEFFICIENT,
this.currentSpeed=s<i?s:i):t&&(this.currentSpeed=t)},
init:function(){var t,i,s,e,n;document.querySelector("."+m.classes.ICON).style.visibility="hidden",
this.adjustDimensions(),
this.setSpeed(),
this.containerEl=document.createElement("div"),
this.containerEl.className=m.classes.CONTAINER,
this.canvas=(t=this.containerEl,
i=this.dimensions.WIDTH,
s=this.dimensions.HEIGHT,
e=m.classes.PLAYER,
(n=document.createElement("canvas")).className=e?m.classes.CANVAS+" "+e:m.classes.CANVAS,n.width=i,n.height=s,t.appendChild(n),n),
this.canvasCtx=this.canvas.getContext("2d"),
this.canvasCtx.fillStyle="#f7f7f7",
this.canvasCtx.fill(),m.updateCanvasScaling(this.canvas),
this.horizon=new D(this.canvas,this.spriteDef,this.dimensions,this.config.GAP_COEFFICIENT),
this.distanceMeter=new c(this.canvas,this.spriteDef.TEXT_SPRITE,this.dimensions.WIDTH),
this.tRex=new f(this.canvas,this.spriteDef.TREX),
this.outerContainerEl.appendChild(this.containerEl),
this.startListening(),this.update(),window.addEventListener(m.events.RESIZE,this.debounceResize.bind(this))},
createTouchController:function(){this.touchController=document.createElement("div"),
this.touchController.className=m.classes.TOUCH_CONTROLLER,
this.touchController.addEventListener(m.events.TOUCHSTART,this),
this.touchController.addEventListener(m.events.TOUCHEND,this)},
debounceResize:function(){this.resizeTimerId_||(this.resizeTimerId_=setInterval(this.adjustDimensions.bind(this),250))},
adjustDimensions:function(){clearInterval(this.resizeTimerId_),
this.resizeTimerId_=null;var t=window.getComputedStyle(this.outerContainerEl),t=Number(t.paddingLeft.substr(0,t.paddingLeft.length-2));
this.dimensions.WIDTH=this.outerContainerEl.offsetWidth-2*t,
this.isArcadeMode()&&(this.dimensions.WIDTH=Math.min(e,this.dimensions.WIDTH),
this.activated)&&this.setArcadeModeContainerScale(),
this.canvas&&(this.canvas.width=this.dimensions.WIDTH,
this.canvas.height=this.dimensions.HEIGHT,m.updateCanvasScaling(this.canvas),
this.distanceMeter.calcXPos(this.dimensions.WIDTH),this.clearCanvas(),this.horizon.update(0,0,!0),
this.tRex.update(0),this.playing||this.crashed||this.paused?(this.containerEl.style.width=this.dimensions.WIDTH+"px",this.containerEl.style.height=this.dimensions.HEIGHT+"px",
this.distanceMeter.update(0,Math.ceil(this.distanceRan)),
this.stop()):this.tRex.draw(0,0),this.crashed)&&this.gameOverPanel&&(this.gameOverPanel.updateDimensions(this.dimensions.WIDTH),
this.gameOverPanel.draw())},playIntro:function(){var t,i;this.activated||this.crashed?this.crashed&&this.restart():(this.playingIntro=!0,this.tRex.playingIntro=!0,t="@-webkit-keyframes intro { from { width:"+f.config.WIDTH+"px }to { width: "+this.dimensions.WIDTH+"px }}",(i=document.createElement("style")).appendChild(document.createTextNode("")),document.head.appendChild(i),i.sheet.insertRule(t,0),
this.containerEl.addEventListener(m.events.ANIM_END,this.startGame.bind(this)),
this.containerEl.style.webkitAnimation="intro .4s ease-out 1 both",
this.containerEl.style.width=this.dimensions.WIDTH+"px",
this.touchController&&this.outerContainerEl.appendChild(this.touchController),
this.playing=!0,this.activated=!0)},
startGame:function(){this.isArcadeMode()&&this.setArcadeMode(),
this.runningTime=0,
this.playingIntro=!1,
this.tRex.playingIntro=!1,
this.containerEl.style.webkitAnimation="",
this.playCount++,document.addEventListener(m.events.VISIBILITY,this.onVisibilityChange.bind(this)),
window.addEventListener(m.events.BLUR,this.onVisibilityChange.bind(this)),
window.addEventListener(m.events.FOCUS,this.onVisibilityChange.bind(this))},
clearCanvas:function(){this.canvasCtx.clearRect(0,0,this.dimensions.WIDTH,this.dimensions.HEIGHT)},
update:function(){this.updatePending=!1;
var t=o(),i=t-(this.time||t);
this.bdayFlashTimer&&(this.bdayFlashTimer<=0?(this.bdayFlashTimer=null,this.tRex.setFlashing(!1),
this.tRex.enableBdayMode(this.spriteDef.TREX_BDAY)):(this.bdayFlashTimer-=i,this.tRex.update(i),i=0)),
this.time=t,this.playing&&(this.clearCanvas(),
this.tRex.jumping&&this.tRex.updateJump(i),
this.runningTime+=i,t=this.runningTime>this.config.CLEAR_TIME,1!=this.tRex.jumpCount||this.playingIntro||this.playIntro(),
this.playingIntro?this.horizon.update(0,this.currentSpeed,t):(i=this.activated?i:0,this.horizon.update(i,this.currentSpeed,t,this.inverted)),t=t&&function(t,i,s){m.defaultDimensions.WIDTH,t.xPos;
var e=new I(i.xPos+1,i.yPos+1,i.config.WIDTH-2,(i.bdayModeActive?i.config.HEIGHT_BDAY:i.config.HEIGHT)-2),n=new I(t.xPos+1,t.yPos+1,t.typeConfig.width*t.size-2,t.typeConfig.height-2);s&&g(s,e,n);
if(E(e,n))for(var h=t.collisionBoxes,o=i.ducking?f.collisionBoxes.DUCKING:f.collisionBoxes.RUNNING,a=0;a<o.length;a++)for(var r=0;r<h.length;r++){var c=l(o[a],e),d=l(h[r],n),u=E(c,d);
if(i.bdayModeActive&&(c.y+=m.config.BDAY_Y_POS_ADJUST),s&&g(s,c,d),u)return[c,d]}return!1}(this.horizon.obstacles[0],this.tRex),m.isBdayModeEnabled()&&t&&"SNACK"==this.horizon.obstacles[0].typeConfig.type&&(this.horizon.enableBdayMode(),
this.tRex.setFlashing(!0),t=!1,this.bdayFlashTimer=this.config.BDAY_FLASH_DURATION),t?this.gameOver():(this.distanceRan+=this.currentSpeed*i/this.msPerFrame,
this.currentSpeed<this.config.MAX_SPEED&&(this.currentSpeed+=this.config.ACCELERATION)),
this.distanceMeter.update(i,Math.ceil(this.distanceRan))&&this.playSound(this.soundFx.SCORE),
this.invertTimer>this.config.INVERT_FADE_DURATION?(this.invertTimer=0,this.invertTrigger=!1,this.invert()):this.invertTimer?this.invertTimer+=i:0<(t=this.distanceMeter.getActualDistance(Math.ceil(this.distanceRan)))&&(this.invertTrigger=!(t%this.config.INVERT_DISTANCE),
this.invertTrigger)&&0===this.invertTimer&&(this.invertTimer+=i,this.invert())),(this.playing||!this.activated&&this.tRex.blinkCount<m.config.MAX_BLINK_COUNT)&&(this.tRex.update(i),
this.scheduleNextUpdate())},handleEvent:function(s){return function(t,i){switch(t){case i.KEYDOWN:case i.TOUCHSTART:case i.POINTERDOWN:this.onKeyDown(s);
break;case i.KEYUP:case i.TOUCHEND:case i.POINTERUP:this.onKeyUp(s)}}.bind(this)(s.type,m.events)},startListening:function(){document.addEventListener(m.events.KEYDOWN,this),
document.addEventListener(m.events.KEYUP,this),this.containerEl.addEventListener(m.events.TOUCHSTART,this),
document.addEventListener(m.events.POINTERDOWN,this),
document.addEventListener(m.events.POINTERUP,this)},
stopListening:function(){document.removeEventListener(m.events.KEYDOWN,this),
document.removeEventListener(m.events.KEYUP,this),
this.touchController&&(this.touchController.removeEventListener(m.events.TOUCHSTART,this),
this.touchController.removeEventListener(m.events.TOUCHEND,this)),
this.containerEl.removeEventListener(m.events.TOUCHSTART,this),
document.removeEventListener(m.events.POINTERDOWN,this),
document.removeEventListener(m.events.POINTERUP,this)},
onKeyDown:function(t){h&&this.playing&&t.preventDefault(),
this.crashed||this.paused?this.crashed&&t.type==m.events.TOUCHSTART&&t.currentTarget==this.containerEl&&this.restart():m.keycodes.JUMP[t.keyCode]||t.type==m.events.TOUCHSTART?(t.preventDefault(),
this.playing||(this.touchController||t.type!=m.events.TOUCHSTART||this.createTouchController(),
this.loadSounds(),this.playing=!0,this.update(),window.errorPageController&&errorPageController.trackEasterEgg()),
this.tRex.jumping||this.tRex.ducking||(this.playSound(this.soundFx.BUTTON_PRESS),
this.tRex.startJump(this.currentSpeed))):this.playing&&m.keycodes.DUCK[t.keyCode]&&(t.preventDefault(),
this.tRex.jumping?this.tRex.setSpeedDrop():this.tRex.jumping||this.tRex.ducking||this.tRex.setDuck(!0))},onKeyUp:function(t){var i,s=String(t.keyCode),e=m.keycodes.JUMP[s]||t.type==m.events.TOUCHEND||t.type==m.events.POINTERUP;
this.isRunning()&&e?this.tRex.endJump():m.keycodes.DUCK[s]?(this.tRex.speedDrop=!1,this.tRex.setDuck(!1)):this.crashed?(i=o()-this.time,(m.keycodes.RESTART[s]||this.isLeftClickOnCanvas(t)||i>=this.config.GAMEOVER_CLEAR_TIME&&m.keycodes.JUMP[s])&&this.restart()):this.paused&&e&&(this.tRex.reset(),this.play())},
isLeftClickOnCanvas:function(t){return null!=t.button&&t.button<2&&t.type==m.events.POINTERUP&&t.target==this.canvas},scheduleNextUpdate:function(){this.updatePending||(this.updatePending=!0,this.raqId=requestAnimationFrame(this.update.bind(this)))},
isRunning:function(){return!!this.raqId},gameOver:function(){this.playSound(this.soundFx.HIT),h&&window.navigator.vibrate&&window.navigator.vibrate(200),this.stop(),this.crashed=!0,this.distanceMeter.achievement=!1,
this.tRex.update(100,f.status.CRASHED),
this.gameOverPanel?this.gameOverPanel.draw():this.gameOverPanel=new p(this.canvas,this.spriteDef.TEXT_SPRITE,this.spriteDef.RESTART,this.dimensions),
this.distanceRan>this.highestScore&&(this.highestScore=Math.ceil(this.distanceRan),this.distanceMeter.setHighScore(this.highestScore)),
this.time=o()},stop:function(){this.playing=!1,this.paused=!0,cancelAnimationFrame(this.raqId),this.raqId=0},
play:function(){this.crashed||(this.playing=!0,this.paused=!1,
this.tRex.update(0,f.status.RUNNING),this.time=o(),this.update())},
restart:function(){this.raqId||(this.playCount++,this.runningTime=0,this.playing=!0,this.paused=!1,this.crashed=!1,this.distanceRan=0,this.setSpeed(this.config.SPEED),this.time=o(),this.containerEl.classList.remove(m.classes.CRASHED),this.clearCanvas(),this.distanceMeter.reset(this.highestScore),this.horizon.reset(),this.tRex.reset(),this.playSound(this.soundFx.BUTTON_PRESS),this.invert(!0),this.update())},isArcadeMode:function(){return!0},setArcadeMode:function(){document.body.classList.add(m.classes.ARCADE_MODE),this.setArcadeModeContainerScale()},setArcadeModeContainerScale:function(){var t=window.innerHeight/this.dimensions.HEIGHT,i=window.innerWidth/this.dimensions.WIDTH,s=Math.max(1,Math.min(t,i)),e=this.dimensions.HEIGHT*s,t=(this.containerEl.style.transform="scale("+s+")","rtl"===document.documentElement.getAttribute("dir"));t&&(this.containerEl.style.transform="scaleX(-1) scale("+s+")"),0<translateElements.length&&translateElements.forEach(function(t){t.style.transform="translateY("+(e-e/s)+"px)"})},onVisibilityChange:function(t){document.hidden||document.webkitHidden||"blur"==t.type||"visible"!=document.visibilityState?this.stop():this.crashed||(this.tRex.reset(),this.play())},playSound:function(t){t&&t.play()},invert:function(t){t?(document.documentElement.classList.toggle(m.classes.INVERTED,!1),this.invertTimer=0,this.inverted=!1):this.inverted=document.documentElement.classList.toggle(m.classes.INVERTED,this.invertTrigger)}},m.updateCanvasScaling=function(t,i,s){var e=t.getContext("2d"),n=Math.floor(window.devicePixelRatio)||1,h=Math.floor(e.webkitBackingStorePixelRatio)||1,o=n/h;
return n!==h?(h=i||t.width,i=s||t.height,t.width=h*o,t.height=i*o,t.style.width=h+"px",t.style.height=i+"px",e.scale(o,o),!0):(1==n&&(t.style.width=t.width+"px",t.style.height=t.height+"px"),!1)},m.isBdayModeEnabled=function(){return!0},p.dimensions={TEXT_X:0,TEXT_Y:13,TEXT_WIDTH:191,TEXT_HEIGHT:11,RESTART_WIDTH:36,RESTART_HEIGHT:32},p.prototype={updateDimensions:function(t,i){this.canvasDimensions.WIDTH=t,i&&(this.canvasDimensions.HEIGHT=i)},draw:function(){var t=p.dimensions,i=this.canvasDimensions.WIDTH/2,s=t.TEXT_X,e=t.TEXT_Y,n=t.TEXT_WIDTH,h=t.TEXT_HEIGHT,o=Math.round(i-t.TEXT_WIDTH/2),a=Math.round((this.canvasDimensions.HEIGHT-25)/3),r=t.TEXT_WIDTH,c=t.TEXT_HEIGHT,d=t.RESTART_WIDTH,u=t.RESTART_HEIGHT,i=i-t.RESTART_WIDTH/2,l=this.canvasDimensions.HEIGHT/2;T&&(e*=2,s*=2,n*=2,h*=2,d*=2,u*=2),s+=this.textImgPos.x,e+=this.textImgPos.y,this.canvasCtx.drawImage(m.imageSprite,s,e,n,h,o,a,r,c),this.canvasCtx.drawImage(m.imageSprite,this.restartImgPos.x,this.restartImgPos.y,d,u,i,l,t.RESTART_WIDTH,t.RESTART_HEIGHT)}},r.MAX_GAP_COEFFICIENT=1.5,r.MAX_OBSTACLE_LENGTH=3,r.prototype={init:function(t){var i;this.cloneCollisionBoxes(),1<this.size&&this.typeConfig.multipleSpeed>t&&(this.size=1),this.width=this.typeConfig.width*this.size,Array.isArray(this.typeConfig.yPos)?(i=h?this.typeConfig.yPosMobile:this.typeConfig.yPos,this.yPos=i[a(0,i.length-1)]):this.yPos=this.typeConfig.yPos,this.draw(),1<this.size&&(this.collisionBoxes[1].width=this.width-this.collisionBoxes[0].width-this.collisionBoxes[2].width,this.collisionBoxes[2].x=this.width-this.collisionBoxes[2].width),this.typeConfig.speedOffset&&(this.speedOffset=.5<Math.random()?this.typeConfig.speedOffset:-this.typeConfig.speedOffset),this.gap=this.getGap(this.gapCoefficient,t)},draw:function(){var t=this.typeConfig.width,i=this.typeConfig.height,s=(T&&(t*=2,i*=2),t*this.size*(.5*(this.size-1))+this.spritePos.x);0<this.currentFrame&&(s+=t*this.currentFrame),this.canvasCtx.drawImage(this.imageSprite,s,this.spritePos.y,t*this.size,i,this.xPos,this.yPos,this.typeConfig.width*this.size,this.typeConfig.height)},update:function(t,i){this.remove||(this.typeConfig.speedOffset&&(i+=this.speedOffset),this.xPos-=Math.floor(i*s/1e3*t),this.typeConfig.numFrames&&(this.timer+=t,this.timer>=this.typeConfig.frameRate)&&(this.currentFrame=this.currentFrame==this.typeConfig.numFrames-1?0:this.currentFrame+1,this.timer=0),this.draw(),this.isVisible())||(this.remove=!0)},getGap:function(t,i){i=Math.round(this.width*i+this.typeConfig.minGap*t);return a(i,Math.round(i*r.MAX_GAP_COEFFICIENT))},isVisible:function(){return 0<this.xPos+this.width},cloneCollisionBoxes:function(){for(var t=this.typeConfig.collisionBoxes,i=t.length-1;0<=i;i--)this.collisionBoxes[i]=new I(t[i].x,t[i].y,t[i].width,t[i].height)}},r.types=[{type:"CACTUS_SMALL",width:17,height:35,yPos:105,multipleSpeed:4,minGap:120,minSpeed:0,collisionBoxes:[new I(0,7,5,27),new I(4,0,6,34),new I(10,4,7,14)]},{type:"CACTUS_LARGE",width:25,height:50,yPos:90,multipleSpeed:7,minGap:120,minSpeed:0,collisionBoxes:[new I(0,12,7,38),new I(8,0,7,49),new I(13,10,10,38)]},{type:"PTERODACTYL",width:46,height:40,yPos:[100,75,50],yPosMobile:[100,50],multipleSpeed:999,minSpeed:8.5,minGap:150,collisionBoxes:[new I(15,15,16,5),new I(18,21,24,6),new I(2,14,4,3),new I(6,10,4,7),new I(10,8,6,9)],numFrames:2,frameRate:1e3/6,speedOffset:.8},{type:"SNACK",width:33,height:42,yPos:85,multipleSpeed:999,minGap:999,minSpeed:0,collisionBoxes:[new I(0,0,40,40)]}],f.config={DROP_VELOCITY:-5,FLASH_OFF:175,FLASH_ON:100,GRAVITY:.6,HEIGHT:47,HEIGHT_BDAY:63,HEIGHT_DUCK:25,INIITAL_JUMP_VELOCITY:-10,INTRO_DURATION:1500,MAX_JUMP_HEIGHT:30,MIN_JUMP_HEIGHT:30,SPEED_DROP_COEFFICIENT:3,SPRITE_WIDTH:262,START_X_POS:50,WIDTH:44,WIDTH_DUCK:59},f.collisionBoxes={DUCKING:[new I(1,18,55,25)],RUNNING:[new I(22,0,17,16),new I(1,18,30,9),new I(10,35,14,8),new I(1,24,29,5),new I(5,30,21,4),new I(9,34,15,4)]},f.status={CRASHED:"CRASHED",DUCKING:"DUCKING",JUMPING:"JUMPING",RUNNING:"RUNNING",WAITING:"WAITING"},f.BLINK_TIMING=7e3,f.animFrames={WAITING:{frames:[44,0],msPerFrame:1e3/3},RUNNING:{frames:[88,132],msPerFrame:1e3/12},CRASHED:{frames:[220],msPerFrame:1e3/60},JUMPING:{frames:[0],msPerFrame:1e3/60},DUCKING:{frames:[264,323],msPerFrame:125}},f.prototype={init:function(){this.groundYPos=m.defaultDimensions.HEIGHT-this.config.HEIGHT-m.config.BOTTOM_PAD,this.yPos=this.groundYPos,this.minJumpHeight=this.groundYPos-this.config.MIN_JUMP_HEIGHT,this.draw(0,0),this.update(0,f.status.WAITING)},enableBdayMode:function(t){this.bdayModeActive=!0,this.spritePos=t,this.imageSprite=m.bdayImageSprite,this.groundYPos=m.defaultDimensions.HEIGHT-this.config.HEIGHT-m.config.BOTTOM_PAD_BDAY,this.yPos-=m.config.BDAY_Y_POS_ADJUST},setFlashing:function(t){this.flashing=t},setJumpVelocity:function(t){this.config.INIITAL_JUMP_VELOCITY=-t,this.config.DROP_VELOCITY=-t/2},update:function(t,i){this.timer+=t,i&&(this.status=i,this.currentFrame=0,this.msPerFrame=f.animFrames[i].msPerFrame,this.currentAnimFrames=f.animFrames[i].frames,i==f.status.WAITING)&&(this.animStartTime=o(),this.setBlinkDelay()),this.playingIntro&&this.xPos<this.config.START_X_POS&&(this.xPos+=Math.round(this.config.START_X_POS/this.config.INTRO_DURATION*t)),this.status==f.status.WAITING?this.blink(o()):this.draw(this.currentAnimFrames[this.currentFrame],0),!this.flashing&&this.timer>=this.msPerFrame&&(this.currentFrame=this.currentFrame==this.currentAnimFrames.length-1?0:this.currentFrame+1,this.timer=0),this.speedDrop&&this.yPos==this.groundYPos&&(this.speedDrop=!1,this.setDuck(!0))},draw:function(t,i){var s=this.ducking&&this.status!=f.status.CRASHED?this.config.WIDTH_DUCK:this.config.WIDTH,e=this.bdayModeActive?this.config.HEIGHT_BDAY:this.config.HEIGHT,n=e;T&&(t*=2,i*=2,s*=2,e*=2),t+=this.spritePos.x,i+=this.spritePos.y,this.flashing&&(this.timer<this.config.FLASH_ON?this.canvasCtx.globalAlpha=.5:this.timer>this.config.FLASH_OFF&&(this.timer=0)),this.ducking&&this.status!=f.status.CRASHED?this.canvasCtx.drawImage(this.imageSprite,t,i,s,e,this.xPos,this.yPos,this.config.WIDTH_DUCK,n):(this.ducking&&this.status==f.status.CRASHED&&this.xPos++,this.canvasCtx.drawImage(this.imageSprite,t,i,s,e,this.xPos,this.yPos,this.config.WIDTH,n)),this.canvasCtx.globalAlpha=1},setBlinkDelay:function(){this.blinkDelay=Math.ceil(Math.random()*f.BLINK_TIMING)},blink:function(t){t-this.animStartTime>=this.blinkDelay&&(this.draw(this.currentAnimFrames[this.currentFrame],0),1==this.currentFrame)&&(this.setBlinkDelay(),this.animStartTime=t,this.blinkCount++)},startJump:function(t){this.jumping||(this.update(0,f.status.JUMPING),this.jumpVelocity=this.config.INIITAL_JUMP_VELOCITY-t/10,this.jumping=!0,this.reachedMinHeight=!1,this.speedDrop=!1)},endJump:function(){this.reachedMinHeight&&this.jumpVelocity<this.config.DROP_VELOCITY&&(this.jumpVelocity=this.config.DROP_VELOCITY)},updateJump:function(t,i){t/=f.animFrames[this.status].msPerFrame;this.speedDrop?this.yPos+=Math.round(this.jumpVelocity*this.config.SPEED_DROP_COEFFICIENT*t):this.yPos+=Math.round(this.jumpVelocity*t),this.jumpVelocity+=this.config.GRAVITY*t,(this.yPos<this.minJumpHeight||this.speedDrop)&&(this.reachedMinHeight=!0),(this.yPos<this.config.MAX_JUMP_HEIGHT||this.speedDrop)&&this.endJump(),this.yPos>this.groundYPos&&(this.reset(),this.jumpCount++)},setSpeedDrop:function(){this.speedDrop=!0,this.jumpVelocity=1},setDuck:function(t){t&&this.status!=f.status.DUCKING?(this.update(0,f.status.DUCKING),this.ducking=!0):this.status==f.status.DUCKING&&(this.update(0,f.status.RUNNING),this.ducking=!1)},reset:function(){this.yPos=this.groundYPos,this.jumpVelocity=0,this.jumping=!1,this.ducking=!1,this.update(0,f.status.RUNNING),this.midair=!1,this.speedDrop=!1,this.jumpCount=0}},c.dimensions={WIDTH:10,HEIGHT:13,DEST_WIDTH:11},c.yPos=[0,13,27,40,53,67,80,93,107,120],c.config={MAX_DISTANCE_UNITS:5,ACHIEVEMENT_DISTANCE:100,COEFFICIENT:.025,FLASH_DURATION:250,FLASH_ITERATIONS:3},c.prototype={init:function(t){var i="";this.calcXPos(t),this.maxScore=this.maxScoreUnits;for(var s=0;s<this.maxScoreUnits;s++)this.draw(s,0),this.defaultString+="0",i+="9";this.maxScore=parseInt(i)},calcXPos:function(t){this.x=t-c.dimensions.DEST_WIDTH*(this.maxScoreUnits+1)},draw:function(t,i,s){var e=c.dimensions.WIDTH,n=c.dimensions.HEIGHT,i=c.dimensions.WIDTH*i,h=0,t=t*c.dimensions.DEST_WIDTH,o=this.y,a=c.dimensions.WIDTH,r=c.dimensions.HEIGHT;T&&(e*=2,n*=2,i*=2),i+=this.spritePos.x,h+=this.spritePos.y,this.canvasCtx.save(),s?(s=this.x-2*this.maxScoreUnits*c.dimensions.WIDTH,this.canvasCtx.translate(s,this.y)):this.canvasCtx.translate(this.x,this.y),this.canvasCtx.drawImage(this.image,i,h,e,n,t,o,a,r),this.canvasCtx.restore()},getActualDistance:function(t){return t?Math.round(t*this.config.COEFFICIENT):0},update:function(t,i){var s=!0,e=!1;if(this.achievement?this.flashIterations<=this.config.FLASH_ITERATIONS?(this.flashTimer+=t,this.flashTimer<this.config.FLASH_DURATION?s=!1:this.flashTimer>2*this.config.FLASH_DURATION&&(this.flashTimer=0,this.flashIterations++)):(this.achievement=!1,this.flashIterations=0,this.flashTimer=0):((i=this.getActualDistance(i))>this.maxScore&&this.maxScoreUnits==this.config.MAX_DISTANCE_UNITS?(this.maxScoreUnits++,this.maxScore=parseInt(this.maxScore+"9")):this.distance=0,0<i?(i%this.config.ACHIEVEMENT_DISTANCE==0&&(this.achievement=!0,e=!(this.flashTimer=0)),t=(this.defaultString+i).substr(-this.maxScoreUnits),this.digits=t.split("")):this.digits=this.defaultString.split("")),s)for(var n=this.digits.length-1;0<=n;n--)this.draw(n,parseInt(this.digits[n]));return this.drawHighScore(),e},drawHighScore:function(){this.canvasCtx.save(),this.canvasCtx.globalAlpha=.8;for(var t=this.highScore.length-1;0<=t;t--)this.draw(t,parseInt(this.highScore[t],10),!0);this.canvasCtx.restore()},setHighScore:function(t){t=this.getActualDistance(t);t=(this.defaultString+t).substr(-this.maxScoreUnits);this.highScore=["10","11",""].concat(t.split(""))},reset:function(){this.update(0),this.achievement=!1}},d.config={HEIGHT:14,HEIGHT_BALLOON:34,MAX_CLOUD_GAP:400,MAX_SKY_LEVEL:30,MIN_CLOUD_GAP:100,MIN_SKY_LEVEL:71,WIDTH:46,WIDTH_BALLOON:16},d.prototype={init:function(){this.yPos=a(d.config.MAX_SKY_LEVEL,d.config.MIN_SKY_LEVEL),this.draw()},draw:function(){this.canvasCtx.save();var t=this.isBalloon?d.config.WIDTH_BALLOON:d.config.WIDTH,i=this.isBalloon?d.config.HEIGHT_BALLOON:d.config.HEIGHT,s=t,e=i;T&&(t*=2,i*=2),this.canvasCtx.drawImage(this.imageSprite,this.spritePos.x,this.spritePos.y,t,i,this.xPos,this.yPos,s,e),this.canvasCtx.restore()},update:function(t){this.remove||(this.xPos-=Math.ceil(t),this.draw(),this.isVisible())||(this.remove=!0)},isVisible:function(){return 0<this.xPos+d.config.WIDTH}},u.config={FADE_SPEED:.035,HEIGHT:40,MOON_SPEED:.25,NUM_STARS:2,STAR_SIZE:9,STAR_SPEED:.3,STAR_MAX_Y:70,WIDTH:20},u.phases=[140,120,100,60,40,20,0],u.prototype={update:function(t,i){if(t&&0==this.opacity&&(this.currentPhase++,this.currentPhase>=u.phases.length)&&(this.currentPhase=0),t&&(this.opacity<1||0==this.opacity)?this.opacity+=u.config.FADE_SPEED:0<this.opacity&&(this.opacity-=u.config.FADE_SPEED),0<this.opacity){if(this.xPos=this.updateXPos(this.xPos,u.config.MOON_SPEED),this.drawStars)for(var s=0;s<u.config.NUM_STARS;s++)this.stars[s].x=this.updateXPos(this.stars[s].x,u.config.STAR_SPEED);this.draw()}else this.opacity=0,this.placeStars();this.drawStars=!0},updateXPos:function(t,i){return t<-u.config.WIDTH?t=this.containerWidth:t-=i,t},draw:function(){var t=3==this.currentPhase?2*u.config.WIDTH:u.config.WIDTH,i=u.config.HEIGHT,s=this.spritePos.x+u.phases[this.currentPhase],e=t,n=u.config.STAR_SIZE,h=m.spriteDefinition.LDPI.STAR.x;if(T&&(t*=2,i*=2,s=this.spritePos.x+2*u.phases[this.currentPhase],n*=2,h=m.spriteDefinition.HDPI.STAR.x),this.canvasCtx.save(),this.canvasCtx.globalAlpha=this.opacity,this.drawStars)for(var o=0;o<u.config.NUM_STARS;o++)this.canvasCtx.drawImage(m.imageSprite,h,this.stars[o].sourceY,n,n,Math.round(this.stars[o].x),this.stars[o].y,u.config.STAR_SIZE,u.config.STAR_SIZE);this.canvasCtx.drawImage(m.imageSprite,s,this.spritePos.y,t,i,Math.round(this.xPos),this.yPos,e,u.config.HEIGHT),this.canvasCtx.globalAlpha=1,this.canvasCtx.restore()},placeStars:function(){for(var t=Math.round(this.containerWidth/u.config.NUM_STARS),i=0;i<u.config.NUM_STARS;i++)this.stars[i]={},this.stars[i].x=a(t*i,t*(i+1)),this.stars[i].y=a(0,u.config.STAR_MAX_Y),this.stars[i].sourceY=T?m.spriteDefinition.HDPI.STAR.y+2*u.config.STAR_SIZE*i:m.spriteDefinition.LDPI.STAR.y+u.config.STAR_SIZE*i},reset:function(){this.currentPhase=0,this.opacity=0,this.update(!1)}},C.dimensions={WIDTH:600,HEIGHT:12,YPOS:127},C.prototype={setSourceDimensions:function(){for(var t in C.dimensions)T?"YPOS"!=t&&(this.sourceDimensions[t]=2*C.dimensions[t]):this.sourceDimensions[t]=C.dimensions[t],this.dimensions[t]=C.dimensions[t];this.xPos=[0,C.dimensions.WIDTH],this.yPos=C.dimensions.YPOS},getRandomType:function(){return Math.random()>this.bumpThreshold?this.dimensions.WIDTH:0},draw:function(){this.canvasCtx.drawImage(m.imageSprite,this.sourceXPos[0],this.spritePos.y,this.sourceDimensions.WIDTH,this.sourceDimensions.HEIGHT,this.xPos[0],this.yPos,this.dimensions.WIDTH,this.dimensions.HEIGHT),this.canvasCtx.drawImage(m.imageSprite,this.sourceXPos[1],this.spritePos.y,this.sourceDimensions.WIDTH,this.sourceDimensions.HEIGHT,this.xPos[1],this.yPos,this.dimensions.WIDTH,this.dimensions.HEIGHT)},updateXPos:function(t,i){var s=t,t=0==t?1:0;this.xPos[s]-=i,this.xPos[t]=this.xPos[s]+this.dimensions.WIDTH,this.xPos[s]<=-this.dimensions.WIDTH&&(this.xPos[s]+=2*this.dimensions.WIDTH,this.xPos[t]=this.xPos[s]-this.dimensions.WIDTH,this.sourceXPos[s]=this.getRandomType()+this.spritePos.x)},update:function(t,i){i=Math.floor(i*(s/1e3)*t);this.xPos[0]<=0?this.updateXPos(0,i):this.updateXPos(1,i),this.draw()},reset:function(){this.xPos[0]=0,this.xPos[1]=C.dimensions.WIDTH}},D.config={BG_CLOUD_SPEED:.2,BUMPY_THRESHOLD:.3,CLOUD_FREQUENCY:.5,HORIZON_HEIGHT:16,MAX_CLOUDS:6},D.prototype={init:function(){this.addCloud(),this.horizonLine=new C(this.canvas,this.spritePos.HORIZON),this.nightMode=new u(this.canvas,this.spritePos.MOON,this.dimensions.WIDTH)},enableBdayMode:function(){this.bdayModeActive=!0,this.removeFirstObstacle()},update:function(t,i,s,e){this.runningTime+=t,this.horizonLine.update(t,i),this.nightMode.update(e),this.updateClouds(t,i),s&&this.updateObstacles(t,i)},updateClouds:function(t,i){var s=this.cloudSpeed/1e3*t*i,t=this.clouds.length;if(t){for(var e=t-1;0<=e;e--)this.clouds[e].update(s);i=this.clouds[t-1];t<this.config.MAX_CLOUDS&&this.dimensions.WIDTH-i.xPos>i.cloudGap&&this.cloudFrequency>Math.random()&&this.addCloud(),this.clouds=this.clouds.filter(function(t){return!t.remove})}else this.addCloud()},updateObstacles:function(t,i){for(var s,e=this.obstacles.slice(0),n=0;n<this.obstacles.length;n++){var h=this.obstacles[n];h.update(t,i),h.remove&&e.shift()}this.obstacles=e,0<this.obstacles.length?(s=this.obstacles[this.obstacles.length-1])&&!s.followingObstacleCreated&&s.isVisible()&&s.xPos+s.width+s.gap<this.dimensions.WIDTH&&(this.addNewObstacle(i),s.followingObstacleCreated=!0):this.addNewObstacle(i)},removeFirstObstacle:function(){this.obstacles.shift()},addNewObstacle:function(t){var i,s=a(0,m.isBdayModeEnabled()&&!this.bdayModeActive?r.types.length-1:r.types.length-2),s=r.types[s];this.duplicateObstacleCheck(s.type)||t<s.minSpeed?this.addNewObstacle(t):(i=this.spritePos[s.type],this.obstacles.push(new r(this.canvasCtx,s,i,this.dimensions,this.gapCoefficient,t,s.width)),this.obstacleHistory.unshift(s.type),1<this.obstacleHistory.length&&this.obstacleHistory.splice(m.config.MAX_OBSTACLE_DUPLICATION))},
duplicateObstacleCheck:function(t){for(var i=0,s=0;s<this.obstacleHistory.length;s++)i=this.obstacleHistory[s]==t?i+1:0;return i>=m.config.MAX_OBSTACLE_DUPLICATION},reset:function(){this.obstacles=[],this.horizonLine.reset(),this.nightMode.reset()},resize:function(t,i){this.canvas.width=t,this.canvas.height=i},addCloud:function(){var t=this.bdayModeActive&&0<a(0,1)?this.spritePos.BALLOON:this.spritePos.CLOUD;this.clouds.push(new d(this.canvas,t,this.dimensions.WIDTH,t==this.spritePos.BALLOON))}}}(),document.addEventListener("DOMContentLoaded",onDocumentLoad)
